### ISSUE TITLE
MN to NISO: appendix element

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2sts#10]
@ronaldtse
In the source xml (https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-en.final.xml) there is `annex/appendix` element:
```
<appendix id="_sample_code" inline-header="false" obligation="informative">
<title>Sample code</title>
<example id="samplecode"><name>Sample Code</name><sourcecode lang="ruby" id="_24e92ae9-4688-4d01-9dd4-03b6867dd956">puts "Hello, world."
%w{a b c}.each do |x| <callout target="_385aa053-2028-4ff6-84a9-37f06d590435">1</callout>
  puts x
end<annotation id="_385aa053-2028-4ff6-84a9-37f06d590435">
<p id="_416b04ea-e3e5-4b6d-a6b7-d31c3d1ef75b">This is an annotation</p>
</annotation></sourcecode>

</example>
</appendix>
```

It displays as:
![изображение](https://user-images.githubusercontent.com/5559926/83286059-ffd6b580-a1e7-11ea-907c-db25b1926baa.png)

In NISO schema I didn't find corresponding element. Which is NISO element should I use for this purpose?

**Comment by ronaldtse** [comment]
Ping @opoudjis for an answer.

**Comment by opoudjis** [comment]
The appendix child of annex is specific to ISO: it is a subsidiary subclause of an annex which is treated, in effect, as an appendix to an appendix. 

Presumably in NISO STS, this is `<sec sec-type="appendix">`. (No, this is not a recommended value in https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/attribute/sec-type.html ; the category of an appendix to an annex is idiosyncratic.)

**Comment by ronaldtse** [comment]
Thanks @opoudjis for the answer (P.S. please don't close this since it is an actionable ticket for @Intelligent2013 )

**Comment by Intelligent2013** [comment]
@opoudjis thank you!
