### ISSUE TITLE
NISO STS validation errors

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn2sts#20]
Please review e.g. the results of converting and validating https://github.com/metanorma/mn2sts-ruby/blob/master/spec/fixtures/test.mn.xml; some of the errors (those involving the `<source>` element) point to incomplete conversion (the source element is retaining the bibitem and citeas attributes, which are illegal in NISO STS.) 

m2sts needs a lot more testing, but that test file was an immediate source of concern.

Bear in mind that in the *general* case, errors cannot be resolved in conversion, because NISO STS and Metanorma have different information models: if Metanorma likes formulas in table headers, and NISO STS does not like disp_formula in that context (which is another error I've seen), well, nothing can be done about that. But we would want to minimise those errors.

**Comment by Intelligent2013** [comment]
@opoudjis 
I've checked an errors regarding element `source` and they arised in version 1.1, but in 1.2 they were fixed. Current version of mn2sts is 1.3.
So result of conversion of test.mn.xml into STS is valid.




> Bear in mind that in the _general_ case, errors cannot be resolved in conversion, because NISO STS and Metanorma have different information models: if Metanorma likes formulas in table headers, and NISO STS does not like disp_formula in that context (which is another error I've seen), well, nothing can be done about that. But we would want to minimise those errors.

In source test.mn.xml:
```xml
<table id="table1">
<name>Maximum permissible mass fraction of defects</name>
<thead>
<tr>
<th rowspan="2" align="left">Defect</th>
<th colspan="4" align="center">Maximum permissible mass fraction of defects in husked rice<br/>
<stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>w</mi><mi>max</mi></msub></math></stem><br/>
%</th>
</tr>
```

In resulted STS NISO:
```xml
<table-wrap position="float" id="tab_1">
<label>Table 1</label>
<caption>
<title>Maximum permissible mass fraction of defects</title>
</caption>
<table width="100%">
<thead>
<tr>
<th rowspan="2" align="left">
<bold>Defect</bold>
</th>
<th colspan="4" align="center">
<bold>Maximum permissible mass fraction of defects in husked rice<break/>
<disp-formula>
<mml:math>
<mml:msub>
<mml:mi>w</mml:mi>
<mml:mi>max</mml:mi>
</mml:msub>
</mml:math>
</disp-formula>
<break/>
%</bold>
</th>
```
And resulted XML is valid. So I don't see an issue with `disp-formula` in `thead`. Could you point me where is the issue?

**Comment by opoudjis** [comment]
It was an error raised when I was validating https://github.com/metanorma/mn2sts-ruby/blob/master/spec/fixtures/test.mn.xml; if it's no longer raised, then fine.
