### ISSUE TITLE
Create sts2mn for converting NISO STS / ISOSTS to Metanorma AsciiDoc or XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2sts#21]
From @Intelligent2013 :

> only one issue. XSLT should produce a few .adoc files - bibdata + body. XSLT 2.0 supports a few resulted documents, so we need to use Saxon XSLT processor.
> The Saxon HE free license can be used for personal use but not commercial use https://www.saxonica.com/documentation/#!conditions.
> Another option is using two XSLT 1.0 (or run `sts2mn` twice) for bibdata and body separately.

We can have a sts2mn program that drives two XSLT 1.0 processes. For most documents we don't even need to split the bibdata.

As described:

```sh
sts2mn CNNNN.xml # => CNNNN.adoc (MN Adoc)
sts2mn --format adoc CNNNN.xml # => CNNNN.adoc (MN Adoc)
sts2mn --format adoc CNNNN.xml --output custom.adoc
sts2mn --format xml CNNNN.xml # => CNNNN.xml (MN XML)
sts2mn --format xml CNNNN.xml --output custom.xml

sts2mn --split-bibdata CNNNN.xml # => CNNNN.adoc (MN Adoc) and CNNNN.rxl (Relaton XML)
```

**Comment by Intelligent2013** [comment]
@ronaldtse I would like to clarify a task.
When output format is 'adoc', then resulted CNNNN.adoc (MN Adoc) contains only bibdata fields and in 'sections' subfolder should be placed .adoc for each section, right?
Or you need one adoc for whole document?

**Comment by Intelligent2013** [comment]
@ronaldtse and could you create a repository 'sts2mn', please. Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse  ~~I'm trying to convert MathML from NISO STS xml into AsciiDoc. But found [here](https://github.com/metanorma/reverse_adoc) that:~~

~~> Metanorma Asciidoctor accepts MathML as a native mathematical format. So you do not need to convert the MathML to AsciiMath.~~

~~Is there possibility to put mathml tags into adoc? or it means something else?~~

~~My idea was copy all mathml formulas into html file, then run `reverse_adoc` to convert it into asciidoc, then replace mathml to asciidoc,~~

Ignore my question. I've found answer here: https://www.metanorma.com/blog/2019-05-29-latex-math-stem/

**Comment by Intelligent2013** [comment]
Done. Initial release available here: https://github.com/metanorma/sts2mn/releases/download/v1.0/sts2mn-1.0.jar
Any further issues regarding sts2mn please add in repository https://github.com/metanorma/sts2mn/
