### ISSUE TITLE
Adopt mn2sts.xsl to produce ISO (non NISO) STS xml

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2sts#22]
As titled.
Source: https://github.com/metanorma/mn2sts/issues/13#issuecomment-670437403

**Comment by ronaldtse** [comment]
@Intelligent2013 do we want to have a separate XSL or the same one with option? What is easier to manage?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 do we want to have a separate XSL or the same one with option? What is easier to manage?

@ronaldtse I want to have one XSL with an option.
