### ISSUE TITLE
Add STS sample test

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2sts#3]
NISO provides a sample of of DIN EN ISO 13849-1:2008 here:
https://github.com/sts4i/sample-documents/tree/master/DIN_EN_ISO_13849-1_2008-12_en

We want to use this as a test. While we can process this, we cannot "reproduce" it or copy out its content.

1. We may need to convert the provided XML file into Metanorma AsciiDoc, as an EN ISO standard. We may need a repo for this document.
(also here for hints on how it is rendered:  https://rispialessandro.onweb.it/it/download/en-iso-13849-1-2008_543ee9c2871c2.pdf)

2. Tailor this provided XML into a single EN ISO version using some script, because we do not currently support "adoptions" like DIN > EN > ISO.

**Comment by Intelligent2013** [comment]
@ronaldtse 

> 1. We may need to convert the provided XML file into Metanorma AsciiDoc, as an EN ISO standard. We may need a repo for this document.

NISO XML DIN EN ISO 13849-1:2008 can be converted into Metanorma AsciiDoc with using of sts2mn-1.0.jar (available [here ](https://github.com/metanorma/sts2mn/releases/download/v1.0/sts2mn-1.0.jar)):

```
java -jar sts2mn-1.0.jar https://github.com/sts4i/sample-documents/raw/master/DIN_EN_ISO_13849-1_2008-12_en/DIN_EN_ISO_13849-1_2008-12_en_TBX.xml
```

After run, the resulted adoc `DIN_EN_ISO_13849-1_2008-12_en_TBX.adoc` will be available in the current folder.

> 2. Tailor this provided XML into a single EN ISO version using some script, because we do not currently support "adoptions" like DIN > EN > ISO.

Do you need XML `single EN ISO version` or adoc?

**Comment by Intelligent2013** [comment]
Update. Correct url to remote xml:
```
java -jar sts2mn-1.1.jar https://raw.githubusercontent.com/sts4i/sample-documents/master/DIN_EN_ISO_13849-1_2008-12_en/DIN_EN_ISO_13849-1_2008-12_en_TBX.xml
```
