### ISSUE TITLE
Question: org.xml.sax.SAXParseException; iso.sts.xml is NOT valid reason

### ISSUE THREAD

**Issue by alemorozov** [metanorma/mn2sts#35]
mn2sts emits `org.xml.sax.SAXParseException` when run with our test file `tests/iso.sts.xml`, generated from [tests/iso.adoc](https://raw.githubusercontent.com/metanorma/metanorma-snap/master/tests/iso.adoc):

```
metanorma compile tests/iso.adoc --agree-to-terms
```

https://github.com/metanorma/metanorma-snap/runs/2527216125?check_suite_focus=true (see "Run for adoc in ./tests/*.adoc; do metanorma compile $adoc --agree-to-terms; done")

To ensure our CI is stable, is this message considered as an error, or it's a normal behavior for such errors?

**Comment by Intelligent2013** [comment]
@alexeymorozov  I can't repeat this issue in my environment. Looks like the issue in generated `./tests/iso.xml`. Could you try to add `cat ./tests/iso.xml` and `cat ./tests/iso.sts.xml` to display content of xmls?

what I did:
- git clone https://github.com/metanorma/metanorma-snap/
- metanorma compile tests/iso.adoc --agree-to-terms
- download https://github.com/metanorma/mn2sts/releases/download/v1.7/mn2sts-1.7.jar
- execute:
```
java -jar mn2sts-1.7.jar --xml-file-in D:\Metanorma\repositories\metanorma-snap\tests\iso.xml --xml-file-out D:\Metanorma\repositories\metanorma-snap\tests\iso.sts.xml 
```
```
Input: XML (D:\Metanorma\repositories\metanorma-snap\tests\iso.xml)
Output: XML (D:\Metanorma\repositories\metanorma-snap\tests\iso.sts.xml), format NISO STS

Transforming...
Validate XML againts XSD NISO-STS-extended-1-MathML3-XSD\NISO-STS-extended-1-mathml3.xsd...
D:\Metanorma\repositories\metanorma-snap\tests\iso.sts.xml is valid.
End!
```

**Comment by alemorozov** [comment]
@Intelligent2013 Reproduced it with mn2sts v1.5.0, and it works with v1.7.0. Created a PR with version upgrade. Thanks for the help! :)
