### ISSUE TITLE
eref to std-ref conversion

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2sts#37]
Source: https://github.com/metanorma/mn-samples-bsi/issues/2

MN XML: <eref citeas="PAS 2035:2019" type="inline"/>

Current:
```xml
<std>
	<std-ref>PAS 2035:2019</std-ref>
</std>
```

Expected result:
```xml
<std std-id="PAS 2035:2019" type="dated">
	<std-ref>PAS 2035:2019</std-ref>
</std>
```

**Comment by Intelligent2013** [comment]
In source STS NISO xmls there are two kind of references:
- with `std-id`:
```xml
<std std-id="iso:std:iso:44001:en" type="undated"><std-ref>ISO 44001<?doi https://doi.org/10.3403/30353016U?></std-ref></std>
```
note 1: sometimes std-id equal to content of std-ref (as in first post), sometimes not (as in this example).
note 2: in bibliography there isn't items with `std-id`.

- without `std-id`:
```xml
<std><std-ref>ISO 44001:2017<?doi https://doi.org/10.3403/30353016?></std-ref> Annex E</std>
```


In the current version, xslt puts attribute `std-id` only in case if there is `bibitem` with `@id` = `eref/@bibitem` value. `std-id` in this case = value from `docidentifier[@type = 'URN']`.

I propose to don't change anything here.

**Comment by ronaldtse** [comment]
In Metanorma we do not differentiate undated and dated references inside the link, but at the bibliographic item. 

As long as we can support a round trip whatever solution works, works.
