### ISSUE TITLE
Attribute id value fixing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2sts#38]
Source: https://github.com/metanorma/mn-samples-bsi/issues/2
Sometimes, xml contains non-valid id like this:
`<term id="term-bill-of-material-(bom)-data-structure"`

Characters `(` and `)` should be replace by `_`.

**Comment by ronaldtse** [comment]
@Intelligent2013 is this a bug for @opoudjis to deal with in MN XML?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is this a bug for @opoudjis to deal with in MN XML?

@ronaldtse actually I don't know. If expected type of the attribute `id` is `ID`, then yes, this is MN xml bug. But without MN xsd we can't to demand it.
In STS DTD, the attribute id has type `ID`.

**Comment by opoudjis** [comment]
The answer is, the expected type of the attribute is indeed xsd:ID. I'll dupe this.
